### ISSUE TITLE
add flag for current home town

### ISSUE THREAD

**Issue by bitboxer** [findoutwho/hasbeen.in#122]

**Comment by bascht** [comment]
:heart_eyes_cat: Thanks, Bodobot! :)

**Comment by bitboxer** [comment]
![images duckduckgo](https://cloud.githubusercontent.com/assets/56195/10687075/9fd7c0c0-796a-11e5-910a-1d0f03b5375e.gif)

**Comment by annismckenzie** [comment]
This has been implemented by @dojobo in #145 – closing.
