### ISSUE TITLE
Plant a tree.

### ISSUE THREAD

**Issue by bascht** [findoutwho/hasbeen.in#131]
![Cedar](http://i.imgur.com/Zm8NrhY.png)

Heroku want's to keep us busy, so we have to [migrate](https://devcenter.heroku.com/articles/cedar-14-migration) to a new tree. We gotta shave this yak, otherwise #129 and #130, (and probably #132, #133 and #134 or even #135 – depending on how busy @skade and me are) won't be deployed.

**Comment by annismckenzie** [comment]
:+1:

**Comment by benben** [comment]
do you need help?

**Comment by bascht** [comment]
@benben If you have time to look into this, I'd be delighted to delegate this task. :dancers:

**Comment by bascht** [comment]
Things seem to go well with Heroku these days. -.- 
![screenshot from 2016-01-05 21-49-31](https://cloud.githubusercontent.com/assets/51264/12127234/4e95b818-b3f6-11e5-95c0-324ef56dc239.png)

**Comment by bascht** [comment]
We have a lift off!

```
-----> Compressing... done, 20.5MB

-----> Launching...

       Released v117

       https://hasbeen-in.herokuapp.com/ deployed to Heroku
```
