### ISSUE TITLE
Map is broken

### ISSUE THREAD

**Issue by eljojo** [findoutwho/hasbeen.in#137]
I think it's for everyone: http://eljojo.hasbeen.in/

![screen shot 2016-01-15 at 16 58 58](https://cloud.githubusercontent.com/assets/491230/12357646/6babf7cc-bba9-11e5-83ce-e9b365c18700.png)

**Comment by bascht** [comment]
:eyeglasses: 

Could be related to a `SensorNotRequired` it'll boak into the JS console. Though Google assured me that: 

> The sensor parameter is no longer required for the Google Maps JavaScript API. It won't prevent the 
> Google Maps JavaScript API from working correctly, but we recommend that you remove the sensor 
> parameter from the script element. 

Investigating.
(As in: I'll probably gonna bug @annismckenzie into looking at this)

**Comment by annismckenzie** [comment]
Oh (j|b)oy.

Let's start by removing the `sensor` GET parameter.

**Comment by bascht** [comment]
Map is no longer broken.
I'll decide we call our cargo culting a fix. Shall we?

**Comment by eljojo** [comment]
bitte! Vielen dank @bascht und @annismckenzie!
a :gift: for you: :candy:

**Comment by bascht** [comment]
:smile_cat:
