### ISSUE TITLE
Let's encrypt all the things

### ISSUE THREAD

**Issue by annismckenzie** [findoutwho/hasbeen.in#148]
It would be really nice to have this available via https.

**Comment by annismckenzie** [comment]
Any ideas on how to get started on this one? Generate a separate Let's encrypt certificate for each one of our travellers? :'D

**Comment by bascht** [comment]
Generating single certificates seems to be the only viable option so far. I'd rather buy every user a speedboat than throwing money at a CA for a "wildcard EV" certificate.

Next thing working against us would be Heroku. They also charge monthly and come to think of it there are [better uses](http://www.jamon.de/Schinken/Pata-Negra-Schinken/Pata-Negra-Bellota-Schinken-Andares-de-la-Dehesa.html) for that yearly fee.

**Comment by annismckenzie** [comment]
You are right (although I really had to laugh about where that link took me) – are you paying for Heroku at this time?

**Comment by bascht** [comment]
Nope. We're still rocking the free tier. Domain name is the only thing that's paid for so far. I'd be okay with paying for hosting, but not with paying for someone executing `openssl` for me.

**Comment by annismckenzie** [comment]
Agreed.

**Comment by bascht** [comment]
Let's wait.®

**Comment by annismckenzie** [comment]
We can do this with alternative names in the certificate for the foreseeable future (before we're getting as big as Facebook, that is) – single certificate, but for all the existing subdomains.

**Comment by bascht** [comment]
Good luck finding a CA that'll let us choose SAN's. :dancers:

**Comment by annismckenzie** [comment]
…still talking about Let's Encrypt. They'll support this »at launch« (whenever that is) if that's not just empty talk.

**Comment by benben** [comment]
Since Let's Encrypt is fully CLI-ified, couldn't we built a "issuing a cert on deploy time" ?

**Comment by annismckenzie** [comment]
Sure, that's not the problem. We're still on Heroku and adding the SSL addon costs $20/month – so that's clearly not an option (really, 20 fu**** dollars?).

**Comment by wikimatze** [comment]
As @benben mention, you can use let's encrypt. Here is a nice tutorial: https://medium.com/@franxyzxyz/setting-up-free-https-with-heroku-ssl-and-lets-encrypt-80cf6eac108e

**Comment by bitboxer** [comment]
If oyu use a payed dyno, SSL is now free and includes a letsencrypt certificate via Heroku SSL: https://devcenter.heroku.com/articles/ssl

**Comment by bascht** [comment]
@wikimatze It's not that easy unfortunately. See [my comment above](https://github.com/findoutwho/hasbeen.in/issues/148#issuecomment-180738808). 

The main domain currently has TLS enabled: https://hasbeen.in/

As we have `n` subdomains, and Let's Encrypt won't support a `*.hasbeen.in` wildcard. We would have to issue certificates for > 40 domains in one go.

@bitboxer Doesn't look like they support wildcards, no?

**Comment by bitboxer** [comment]
LetsEncrypt does not support wildcards. With heroku it depends on how you setup the subdomains. If the subdomain is configured in the "Domains and certificates" section in the settings, it will be added to the certificate.

**Comment by bitboxer** [comment]
Letsencrypt can collect several domains into one certificate. Look at the cert for bodo.tasche.me for example to see a long list of domains.

**Comment by wikimatze** [comment]
Too bad :(

**Comment by bascht** [comment]
@bitboxer I *do* know that Let's Encrypt can verify multiple domains per certificate. But what would the workflow be?

* If we add a new user, we'd have to ensure that Domain Verification + Certificate installation can be done during one dyno rebuild
* All the current howto's for Heroku seem to involve manual steps for refreshing the certificate & I do not want to do that every 90 days.

One (tbh quite hacky way) would be to set up a https://traefik.io proxy in front of hasbeen.in and let it handle ACME on the fly.

**Comment by bitboxer** [comment]
The refresh of the certificate is done automatically. See here:

https://devcenter.heroku.com/articles/automated-certificate-management

But read the known limitations there.

I think the workflow would be: add a new subdomain, let heroku handle the rest. With the one problem that the ACM only supports up to 100 subdomains per certificate. If you have more than 100 users, you would need to switch to something else.

**Comment by bascht** [comment]
I might repeat myself here: Heroku doesn't look like a good approach for our use case. I don't want to manually add all the users into the domain config, let alone maintain the list. :smile:

**Comment by bitboxer** [comment]
I just wanted to point out how the workflow would look like. You said you would have to refresh the certificate every 90 days, but that part is already covered through heroku automatically. And yes, adding new users would mean adding a new subdomain. The only alternative I see is to script something that does this completely automatic and use a ssl proxy. But i don't know if that doesn't cost more time than it saves you. If you would add 1 new user every week, then it might do it. But at the current growth rate? Nope, don't think so 😉 .

**Comment by bascht** [comment]
The _refresh every 90 days_ bit referred to Let's Encrypt. ;)
But now as we talk about it, …let me try something else. :grimacing:

**Comment by bascht** [comment]
Turns out a simple Cloudfront distribution will do the trick. Nowadays everyone and their dog operates a CA, so Amazon will gladly issue a certificate for `*.hasbeen.in`. :smile:

**Comment by bascht** [comment]
**Lukin gud.**

![screenshot_20170601_180228](https://cloud.githubusercontent.com/assets/51264/26688988/7c2fe9fa-46f4-11e7-8843-412acd8337a8.png)

**Comment by bitboxer** [comment]
![](https://media.giphy.com/media/vtVpHbnPi9TLa/giphy.gif)

**Comment by bascht** [comment]
Meanwhile: https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579 :D
