### ISSUE TITLE
Lower case city name in URL triggers wrong home town + faulty display

### ISSUE THREAD

**Issue by dojobo** [findoutwho/hasbeen.in#151]
it knows he's been there but
- it doesn't display the name of the city ("Bascht has been in .")
- it thinks it's his current hometown

must be a case issue...

**Comment by bitboxer** [comment]
This works: http://bascht.hasbeen.in/Berlin

**Comment by dojobo** [comment]
right, but i thought it should be case insensitive

**Comment by bascht** [comment]
Alright. Finally dug my way through this shoddy hotel wifi. :rabbit2: 
You might be on to something with the case sensitivity (http://bascht.hasbeen.in/munich looks the same and I do have too many home towns. :dancers: )

**Comment by bascht** [comment]
Refs #122
